version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  pre_build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Static code analysis with flake8 and pylint
          command: |
            pip install flake8 pylint
            flake8 main.py
            pylint main.py
      - run:
          name: Check JavaScript dependencies (if exists)
          command: |
            sudo apt-get update && sudo apt-get install -y npm
            npm install
            npm audit || true

  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Build source code
          command: |
            echo "Compiling source code (placeholder, Python doesn't need compilation)"

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run unit tests with pytest
          command: pytest tests --junitxml=test_results/results.xml
      - run:
          name: Run integration tests (placeholder for Selenium)
          command: |
            echo "Placeholder for Selenium integration tests"

  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            sudo apt-get update && sudo apt-get install -y docker.io
            docker build -t my-app:latest .
      - run:
          name: Run Docker container
          command: docker run -d -p 8080:8080 my-app:latest

workflows:
  version: 2
  pipeline:
    jobs:
      - pre_build
      - build:
          requires:
            - pre_build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
